package com.amazonaws.glue.catalog.metastore;

import com.amazonaws.AmazonWebServiceRequest;
import com.amazonaws.ResponseMetadata;
import com.amazonaws.services.glue.AWSGlue;
import com.amazonaws.services.glue.model.*;

/**
 * Base decorator for AWSGlue interface. It doesn't decorate any functionality but just proxy all methods to
 * decoratedAwsGlue. It should be used as a parent for specific decorators where only necessary methods are overwritten
 * and decorated.
 * All @Override methods are generated by IntelliJ IDEA.
 */
public class AWSGlueDecoratorBase implements AWSGlue {
    private AWSGlue decoratedAwsGlue;

    public AWSGlueDecoratorBase(AWSGlue awsGlueToBeDecorated) {
        this.decoratedAwsGlue = awsGlueToBeDecorated;
    }

    @Override
    public BatchCreatePartitionResult batchCreatePartition(BatchCreatePartitionRequest batchCreatePartitionRequest) {
        return decoratedAwsGlue.batchCreatePartition(batchCreatePartitionRequest);
    }

    @Override
    public BatchDeleteConnectionResult batchDeleteConnection(BatchDeleteConnectionRequest batchDeleteConnectionRequest) {
        return decoratedAwsGlue.batchDeleteConnection(batchDeleteConnectionRequest);
    }

    @Override
    public BatchDeletePartitionResult batchDeletePartition(BatchDeletePartitionRequest batchDeletePartitionRequest) {
        return decoratedAwsGlue.batchDeletePartition(batchDeletePartitionRequest);
    }

    @Override
    public BatchDeleteTableResult batchDeleteTable(BatchDeleteTableRequest batchDeleteTableRequest) {
        return decoratedAwsGlue.batchDeleteTable(batchDeleteTableRequest);
    }

    @Override
    public BatchDeleteTableVersionResult batchDeleteTableVersion(BatchDeleteTableVersionRequest batchDeleteTableVersionRequest) {
        return decoratedAwsGlue.batchDeleteTableVersion(batchDeleteTableVersionRequest);
    }

    @Override
    public BatchGetBlueprintsResult batchGetBlueprints(BatchGetBlueprintsRequest batchGetBlueprintsRequest) {
        return null;
    }

    @Override
    public BatchGetCrawlersResult batchGetCrawlers(BatchGetCrawlersRequest batchGetCrawlersRequest) {
        return decoratedAwsGlue.batchGetCrawlers(batchGetCrawlersRequest);
    }

    @Override
    public BatchGetCustomEntityTypesResult batchGetCustomEntityTypes(BatchGetCustomEntityTypesRequest batchGetCustomEntityTypesRequest) {
        return null;
    }

    @Override
    public BatchGetDevEndpointsResult batchGetDevEndpoints(BatchGetDevEndpointsRequest batchGetDevEndpointsRequest) {
        return decoratedAwsGlue.batchGetDevEndpoints(batchGetDevEndpointsRequest);
    }

    @Override
    public BatchGetJobsResult batchGetJobs(BatchGetJobsRequest batchGetJobsRequest) {
        return decoratedAwsGlue.batchGetJobs(batchGetJobsRequest);
    }

    @Override
    public BatchGetPartitionResult batchGetPartition(BatchGetPartitionRequest batchGetPartitionRequest) {
        return decoratedAwsGlue.batchGetPartition(batchGetPartitionRequest);
    }

    @Override
    public BatchGetTriggersResult batchGetTriggers(BatchGetTriggersRequest batchGetTriggersRequest) {
        return decoratedAwsGlue.batchGetTriggers(batchGetTriggersRequest);
    }

    @Override
    public BatchGetWorkflowsResult batchGetWorkflows(BatchGetWorkflowsRequest batchGetWorkflowsRequest) {
        return decoratedAwsGlue.batchGetWorkflows(batchGetWorkflowsRequest);
    }

    @Override
    public BatchStopJobRunResult batchStopJobRun(BatchStopJobRunRequest batchStopJobRunRequest) {
        return decoratedAwsGlue.batchStopJobRun(batchStopJobRunRequest);
    }

    @Override
    public BatchUpdatePartitionResult batchUpdatePartition(BatchUpdatePartitionRequest batchUpdatePartitionRequest) {
        return decoratedAwsGlue.batchUpdatePartition(batchUpdatePartitionRequest);
    }

    @Override
    public CancelMLTaskRunResult cancelMLTaskRun(CancelMLTaskRunRequest cancelMLTaskRunRequest) {
        return decoratedAwsGlue.cancelMLTaskRun(cancelMLTaskRunRequest);
    }

    @Override
    public CancelStatementResult cancelStatement(CancelStatementRequest cancelStatementRequest) {
        return null;
    }

    @Override
    public CheckSchemaVersionValidityResult checkSchemaVersionValidity(CheckSchemaVersionValidityRequest checkSchemaVersionValidityRequest) {
        return decoratedAwsGlue.checkSchemaVersionValidity(checkSchemaVersionValidityRequest);
    }

    @Override
    public CreateBlueprintResult createBlueprint(CreateBlueprintRequest createBlueprintRequest) {
        return null;
    }

    @Override
    public CreateClassifierResult createClassifier(CreateClassifierRequest createClassifierRequest) {
        return decoratedAwsGlue.createClassifier(createClassifierRequest);
    }

    @Override
    public CreateConnectionResult createConnection(CreateConnectionRequest createConnectionRequest) {
        return decoratedAwsGlue.createConnection(createConnectionRequest);
    }

    @Override
    public CreateCrawlerResult createCrawler(CreateCrawlerRequest createCrawlerRequest) {
        return decoratedAwsGlue.createCrawler(createCrawlerRequest);
    }

    @Override
    public CreateCustomEntityTypeResult createCustomEntityType(CreateCustomEntityTypeRequest createCustomEntityTypeRequest) {
        return null;
    }

    @Override
    public CreateDatabaseResult createDatabase(CreateDatabaseRequest createDatabaseRequest) {
        return decoratedAwsGlue.createDatabase(createDatabaseRequest);
    }

    @Override
    public CreateDevEndpointResult createDevEndpoint(CreateDevEndpointRequest createDevEndpointRequest) {
        return decoratedAwsGlue.createDevEndpoint(createDevEndpointRequest);
    }

    @Override
    public CreateJobResult createJob(CreateJobRequest createJobRequest) {
        return decoratedAwsGlue.createJob(createJobRequest);
    }

    @Override
    public CreateMLTransformResult createMLTransform(CreateMLTransformRequest createMLTransformRequest) {
        return decoratedAwsGlue.createMLTransform(createMLTransformRequest);
    }

    @Override
    public CreatePartitionResult createPartition(CreatePartitionRequest createPartitionRequest) {
        return decoratedAwsGlue.createPartition(createPartitionRequest);
    }

    @Override
    public CreatePartitionIndexResult createPartitionIndex(CreatePartitionIndexRequest createPartitionIndexRequest) {
        return decoratedAwsGlue.createPartitionIndex(createPartitionIndexRequest);
    }

    @Override
    public CreateRegistryResult createRegistry(CreateRegistryRequest createRegistryRequest) {
        return decoratedAwsGlue.createRegistry(createRegistryRequest);
    }

    @Override
    public CreateSchemaResult createSchema(CreateSchemaRequest createSchemaRequest) {
        return decoratedAwsGlue.createSchema(createSchemaRequest);
    }

    @Override
    public CreateScriptResult createScript(CreateScriptRequest createScriptRequest) {
        return decoratedAwsGlue.createScript(createScriptRequest);
    }

    @Override
    public CreateSecurityConfigurationResult createSecurityConfiguration(CreateSecurityConfigurationRequest createSecurityConfigurationRequest) {
        return decoratedAwsGlue.createSecurityConfiguration(createSecurityConfigurationRequest);
    }

    @Override
    public CreateSessionResult createSession(CreateSessionRequest createSessionRequest) {
        return null;
    }

    @Override
    public CreateTableResult createTable(CreateTableRequest createTableRequest) {
        return decoratedAwsGlue.createTable(createTableRequest);
    }

    @Override
    public CreateTriggerResult createTrigger(CreateTriggerRequest createTriggerRequest) {
        return decoratedAwsGlue.createTrigger(createTriggerRequest);
    }

    @Override
    public CreateUserDefinedFunctionResult createUserDefinedFunction(CreateUserDefinedFunctionRequest createUserDefinedFunctionRequest) {
        return decoratedAwsGlue.createUserDefinedFunction(createUserDefinedFunctionRequest);
    }

    @Override
    public CreateWorkflowResult createWorkflow(CreateWorkflowRequest createWorkflowRequest) {
        return decoratedAwsGlue.createWorkflow(createWorkflowRequest);
    }

    @Override
    public DeleteBlueprintResult deleteBlueprint(DeleteBlueprintRequest deleteBlueprintRequest) {
        return null;
    }

    @Override
    public DeleteClassifierResult deleteClassifier(DeleteClassifierRequest deleteClassifierRequest) {
        return decoratedAwsGlue.deleteClassifier(deleteClassifierRequest);
    }

    @Override
    public DeleteColumnStatisticsForPartitionResult deleteColumnStatisticsForPartition(DeleteColumnStatisticsForPartitionRequest deleteColumnStatisticsForPartitionRequest) {
        return decoratedAwsGlue.deleteColumnStatisticsForPartition(deleteColumnStatisticsForPartitionRequest);
    }

    @Override
    public DeleteColumnStatisticsForTableResult deleteColumnStatisticsForTable(DeleteColumnStatisticsForTableRequest deleteColumnStatisticsForTableRequest) {
        return decoratedAwsGlue.deleteColumnStatisticsForTable(deleteColumnStatisticsForTableRequest);
    }

    @Override
    public DeleteConnectionResult deleteConnection(DeleteConnectionRequest deleteConnectionRequest) {
        return decoratedAwsGlue.deleteConnection(deleteConnectionRequest);
    }

    @Override
    public DeleteCrawlerResult deleteCrawler(DeleteCrawlerRequest deleteCrawlerRequest) {
        return decoratedAwsGlue.deleteCrawler(deleteCrawlerRequest);
    }

    @Override
    public DeleteCustomEntityTypeResult deleteCustomEntityType(DeleteCustomEntityTypeRequest deleteCustomEntityTypeRequest) {
        return null;
    }

    @Override
    public DeleteDatabaseResult deleteDatabase(DeleteDatabaseRequest deleteDatabaseRequest) {
        return decoratedAwsGlue.deleteDatabase(deleteDatabaseRequest);
    }

    @Override
    public DeleteDevEndpointResult deleteDevEndpoint(DeleteDevEndpointRequest deleteDevEndpointRequest) {
        return decoratedAwsGlue.deleteDevEndpoint(deleteDevEndpointRequest);
    }

    @Override
    public DeleteJobResult deleteJob(DeleteJobRequest deleteJobRequest) {
        return decoratedAwsGlue.deleteJob(deleteJobRequest);
    }

    @Override
    public DeleteMLTransformResult deleteMLTransform(DeleteMLTransformRequest deleteMLTransformRequest) {
        return decoratedAwsGlue.deleteMLTransform(deleteMLTransformRequest);
    }

    @Override
    public DeletePartitionResult deletePartition(DeletePartitionRequest deletePartitionRequest) {
        return decoratedAwsGlue.deletePartition(deletePartitionRequest);
    }

    @Override
    public DeletePartitionIndexResult deletePartitionIndex(DeletePartitionIndexRequest deletePartitionIndexRequest) {
        return decoratedAwsGlue.deletePartitionIndex(deletePartitionIndexRequest);
    }

    @Override
    public DeleteRegistryResult deleteRegistry(DeleteRegistryRequest deleteRegistryRequest) {
        return decoratedAwsGlue.deleteRegistry(deleteRegistryRequest);
    }

    @Override
    public DeleteResourcePolicyResult deleteResourcePolicy(DeleteResourcePolicyRequest deleteResourcePolicyRequest) {
        return decoratedAwsGlue.deleteResourcePolicy(deleteResourcePolicyRequest);
    }

    @Override
    public DeleteSchemaResult deleteSchema(DeleteSchemaRequest deleteSchemaRequest) {
        return decoratedAwsGlue.deleteSchema(deleteSchemaRequest);
    }

    @Override
    public DeleteSchemaVersionsResult deleteSchemaVersions(DeleteSchemaVersionsRequest deleteSchemaVersionsRequest) {
        return decoratedAwsGlue.deleteSchemaVersions(deleteSchemaVersionsRequest);
    }

    @Override
    public DeleteSecurityConfigurationResult deleteSecurityConfiguration(DeleteSecurityConfigurationRequest deleteSecurityConfigurationRequest) {
        return decoratedAwsGlue.deleteSecurityConfiguration(deleteSecurityConfigurationRequest);
    }

    @Override
    public DeleteSessionResult deleteSession(DeleteSessionRequest deleteSessionRequest) {
        return null;
    }

    @Override
    public DeleteTableResult deleteTable(DeleteTableRequest deleteTableRequest) {
        return decoratedAwsGlue.deleteTable(deleteTableRequest);
    }

    @Override
    public DeleteTableVersionResult deleteTableVersion(DeleteTableVersionRequest deleteTableVersionRequest) {
        return decoratedAwsGlue.deleteTableVersion(deleteTableVersionRequest);
    }

    @Override
    public DeleteTriggerResult deleteTrigger(DeleteTriggerRequest deleteTriggerRequest) {
        return decoratedAwsGlue.deleteTrigger(deleteTriggerRequest);
    }

    @Override
    public DeleteUserDefinedFunctionResult deleteUserDefinedFunction(DeleteUserDefinedFunctionRequest deleteUserDefinedFunctionRequest) {
        return decoratedAwsGlue.deleteUserDefinedFunction(deleteUserDefinedFunctionRequest);
    }

    @Override
    public DeleteWorkflowResult deleteWorkflow(DeleteWorkflowRequest deleteWorkflowRequest) {
        return decoratedAwsGlue.deleteWorkflow(deleteWorkflowRequest);
    }

    @Override
    public GetBlueprintResult getBlueprint(GetBlueprintRequest getBlueprintRequest) {
        return null;
    }

    @Override
    public GetBlueprintRunResult getBlueprintRun(GetBlueprintRunRequest getBlueprintRunRequest) {
        return null;
    }

    @Override
    public GetBlueprintRunsResult getBlueprintRuns(GetBlueprintRunsRequest getBlueprintRunsRequest) {
        return null;
    }

    @Override
    public GetCatalogImportStatusResult getCatalogImportStatus(GetCatalogImportStatusRequest getCatalogImportStatusRequest) {
        return decoratedAwsGlue.getCatalogImportStatus(getCatalogImportStatusRequest);
    }

    @Override
    public GetClassifierResult getClassifier(GetClassifierRequest getClassifierRequest) {
        return decoratedAwsGlue.getClassifier(getClassifierRequest);
    }

    @Override
    public GetClassifiersResult getClassifiers(GetClassifiersRequest getClassifiersRequest) {
        return decoratedAwsGlue.getClassifiers(getClassifiersRequest);
    }

    @Override
    public GetColumnStatisticsForPartitionResult getColumnStatisticsForPartition(GetColumnStatisticsForPartitionRequest getColumnStatisticsForPartitionRequest) {
        return decoratedAwsGlue.getColumnStatisticsForPartition(getColumnStatisticsForPartitionRequest);
    }

    @Override
    public GetColumnStatisticsForTableResult getColumnStatisticsForTable(GetColumnStatisticsForTableRequest getColumnStatisticsForTableRequest) {
        return decoratedAwsGlue.getColumnStatisticsForTable(getColumnStatisticsForTableRequest);
    }

    @Override
    public GetConnectionResult getConnection(GetConnectionRequest getConnectionRequest) {
        return decoratedAwsGlue.getConnection(getConnectionRequest);
    }

    @Override
    public GetConnectionsResult getConnections(GetConnectionsRequest getConnectionsRequest) {
        return decoratedAwsGlue.getConnections(getConnectionsRequest);
    }

    @Override
    public GetCrawlerResult getCrawler(GetCrawlerRequest getCrawlerRequest) {
        return decoratedAwsGlue.getCrawler(getCrawlerRequest);
    }

    @Override
    public GetCrawlerMetricsResult getCrawlerMetrics(GetCrawlerMetricsRequest getCrawlerMetricsRequest) {
        return decoratedAwsGlue.getCrawlerMetrics(getCrawlerMetricsRequest);
    }

    @Override
    public GetCrawlersResult getCrawlers(GetCrawlersRequest getCrawlersRequest) {
        return decoratedAwsGlue.getCrawlers(getCrawlersRequest);
    }

    @Override
    public GetCustomEntityTypeResult getCustomEntityType(GetCustomEntityTypeRequest getCustomEntityTypeRequest) {
        return null;
    }

    @Override
    public GetDataCatalogEncryptionSettingsResult getDataCatalogEncryptionSettings(GetDataCatalogEncryptionSettingsRequest getDataCatalogEncryptionSettingsRequest) {
        return decoratedAwsGlue.getDataCatalogEncryptionSettings(getDataCatalogEncryptionSettingsRequest);
    }

    @Override
    public GetDatabaseResult getDatabase(GetDatabaseRequest getDatabaseRequest) {
        return decoratedAwsGlue.getDatabase(getDatabaseRequest);
    }

    @Override
    public GetDatabasesResult getDatabases(GetDatabasesRequest getDatabasesRequest) {
        return decoratedAwsGlue.getDatabases(getDatabasesRequest);
    }

    @Override
    public GetDataflowGraphResult getDataflowGraph(GetDataflowGraphRequest getDataflowGraphRequest) {
        return decoratedAwsGlue.getDataflowGraph(getDataflowGraphRequest);
    }

    @Override
    public GetDevEndpointResult getDevEndpoint(GetDevEndpointRequest getDevEndpointRequest) {
        return decoratedAwsGlue.getDevEndpoint(getDevEndpointRequest);
    }

    @Override
    public GetDevEndpointsResult getDevEndpoints(GetDevEndpointsRequest getDevEndpointsRequest) {
        return decoratedAwsGlue.getDevEndpoints(getDevEndpointsRequest);
    }

    @Override
    public GetJobResult getJob(GetJobRequest getJobRequest) {
        return decoratedAwsGlue.getJob(getJobRequest);
    }

    @Override
    public GetJobBookmarkResult getJobBookmark(GetJobBookmarkRequest getJobBookmarkRequest) {
        return decoratedAwsGlue.getJobBookmark(getJobBookmarkRequest);
    }

    @Override
    public GetJobRunResult getJobRun(GetJobRunRequest getJobRunRequest) {
        return decoratedAwsGlue.getJobRun(getJobRunRequest);
    }

    @Override
    public GetJobRunsResult getJobRuns(GetJobRunsRequest getJobRunsRequest) {
        return decoratedAwsGlue.getJobRuns(getJobRunsRequest);
    }

    @Override
    public GetJobsResult getJobs(GetJobsRequest getJobsRequest) {
        return decoratedAwsGlue.getJobs(getJobsRequest);
    }

    @Override
    public GetMLTaskRunResult getMLTaskRun(GetMLTaskRunRequest getMLTaskRunRequest) {
        return decoratedAwsGlue.getMLTaskRun(getMLTaskRunRequest);
    }

    @Override
    public GetMLTaskRunsResult getMLTaskRuns(GetMLTaskRunsRequest getMLTaskRunsRequest) {
        return decoratedAwsGlue.getMLTaskRuns(getMLTaskRunsRequest);
    }

    @Override
    public GetMLTransformResult getMLTransform(GetMLTransformRequest getMLTransformRequest) {
        return decoratedAwsGlue.getMLTransform(getMLTransformRequest);
    }

    @Override
    public GetMLTransformsResult getMLTransforms(GetMLTransformsRequest getMLTransformsRequest) {
        return decoratedAwsGlue.getMLTransforms(getMLTransformsRequest);
    }

    @Override
    public GetMappingResult getMapping(GetMappingRequest getMappingRequest) {
        return decoratedAwsGlue.getMapping(getMappingRequest);
    }


    @Override
    public GetPartitionIndexesResult getPartitionIndexes(GetPartitionIndexesRequest getPartitionIndexesRequest) {
        return decoratedAwsGlue.getPartitionIndexes(getPartitionIndexesRequest);
    }

    @Override
    public GetPartitionResult getPartition(GetPartitionRequest getPartitionRequest) {
        return decoratedAwsGlue.getPartition(getPartitionRequest);
    }

    @Override
    public GetPartitionsResult getPartitions(GetPartitionsRequest getPartitionsRequest) {
        return decoratedAwsGlue.getPartitions(getPartitionsRequest);
    }

    @Override
    public GetPlanResult getPlan(GetPlanRequest getPlanRequest) {
        return decoratedAwsGlue.getPlan(getPlanRequest);
    }

    @Override
    public GetRegistryResult getRegistry(GetRegistryRequest getRegistryRequest) {
        return decoratedAwsGlue.getRegistry(getRegistryRequest);
    }

    @Override
    public GetResourcePolicyResult getResourcePolicy(GetResourcePolicyRequest getResourcePolicyRequest) {
        return decoratedAwsGlue.getResourcePolicy(getResourcePolicyRequest);
    }

    @Override
    public GetSchemaResult getSchema(GetSchemaRequest getSchemaRequest) {
        return decoratedAwsGlue.getSchema(getSchemaRequest);
    }

    @Override
    public GetSchemaByDefinitionResult getSchemaByDefinition(GetSchemaByDefinitionRequest getSchemaByDefinitionRequest) {
        return decoratedAwsGlue.getSchemaByDefinition(getSchemaByDefinitionRequest);
    }

    @Override
    public GetSchemaVersionResult getSchemaVersion(GetSchemaVersionRequest getSchemaVersionRequest) {
        return decoratedAwsGlue.getSchemaVersion(getSchemaVersionRequest);
    }

    @Override
    public GetSchemaVersionsDiffResult getSchemaVersionsDiff(GetSchemaVersionsDiffRequest getSchemaVersionsDiffRequest) {
        return decoratedAwsGlue.getSchemaVersionsDiff(getSchemaVersionsDiffRequest);
    }

    @Override
    public GetSecurityConfigurationResult getSecurityConfiguration(GetSecurityConfigurationRequest getSecurityConfigurationRequest) {
        return decoratedAwsGlue.getSecurityConfiguration(getSecurityConfigurationRequest);
    }

    @Override
    public GetSecurityConfigurationsResult getSecurityConfigurations(GetSecurityConfigurationsRequest getSecurityConfigurationsRequest) {
        return decoratedAwsGlue.getSecurityConfigurations(getSecurityConfigurationsRequest);
    }

    @Override
    public GetSessionResult getSession(GetSessionRequest getSessionRequest) {
        return null;
    }

    @Override
    public GetStatementResult getStatement(GetStatementRequest getStatementRequest) {
        return null;
    }

    @Override
    public GetTableResult getTable(GetTableRequest getTableRequest) {
        return decoratedAwsGlue.getTable(getTableRequest);
    }

    @Override
    public GetTableVersionResult getTableVersion(GetTableVersionRequest getTableVersionRequest) {
        return decoratedAwsGlue.getTableVersion(getTableVersionRequest);
    }

    @Override
    public GetTableVersionsResult getTableVersions(GetTableVersionsRequest getTableVersionsRequest) {
        return decoratedAwsGlue.getTableVersions(getTableVersionsRequest);
    }

    @Override
    public GetTablesResult getTables(GetTablesRequest getTablesRequest) {
        return decoratedAwsGlue.getTables(getTablesRequest);
    }

    @Override
    public GetTagsResult getTags(GetTagsRequest getTagsRequest) {
        return decoratedAwsGlue.getTags(getTagsRequest);
    }

    @Override
    public GetTriggerResult getTrigger(GetTriggerRequest getTriggerRequest) {
        return decoratedAwsGlue.getTrigger(getTriggerRequest);
    }

    @Override
    public GetTriggersResult getTriggers(GetTriggersRequest getTriggersRequest) {
        return decoratedAwsGlue.getTriggers(getTriggersRequest);
    }

    @Override
    public GetUnfilteredPartitionMetadataResult getUnfilteredPartitionMetadata(GetUnfilteredPartitionMetadataRequest getUnfilteredPartitionMetadataRequest) {
        return null;
    }

    @Override
    public GetUnfilteredPartitionsMetadataResult getUnfilteredPartitionsMetadata(GetUnfilteredPartitionsMetadataRequest getUnfilteredPartitionsMetadataRequest) {
        return null;
    }

    @Override
    public GetUnfilteredTableMetadataResult getUnfilteredTableMetadata(GetUnfilteredTableMetadataRequest getUnfilteredTableMetadataRequest) {
        return null;
    }

    @Override
    public GetUserDefinedFunctionResult getUserDefinedFunction(GetUserDefinedFunctionRequest getUserDefinedFunctionRequest) {
        return decoratedAwsGlue.getUserDefinedFunction(getUserDefinedFunctionRequest);
    }

    @Override
    public GetUserDefinedFunctionsResult getUserDefinedFunctions(GetUserDefinedFunctionsRequest getUserDefinedFunctionsRequest) {
        return decoratedAwsGlue.getUserDefinedFunctions(getUserDefinedFunctionsRequest);
    }

    @Override
    public GetWorkflowResult getWorkflow(GetWorkflowRequest getWorkflowRequest) {
        return decoratedAwsGlue.getWorkflow(getWorkflowRequest);
    }

    @Override
    public GetWorkflowRunResult getWorkflowRun(GetWorkflowRunRequest getWorkflowRunRequest) {
        return decoratedAwsGlue.getWorkflowRun(getWorkflowRunRequest);
    }

    @Override
    public GetWorkflowRunPropertiesResult getWorkflowRunProperties(GetWorkflowRunPropertiesRequest getWorkflowRunPropertiesRequest) {
        return decoratedAwsGlue.getWorkflowRunProperties(getWorkflowRunPropertiesRequest);
    }

    @Override
    public GetWorkflowRunsResult getWorkflowRuns(GetWorkflowRunsRequest getWorkflowRunsRequest) {
        return decoratedAwsGlue.getWorkflowRuns(getWorkflowRunsRequest);
    }

    @Override
    public ImportCatalogToGlueResult importCatalogToGlue(ImportCatalogToGlueRequest importCatalogToGlueRequest) {
        return decoratedAwsGlue.importCatalogToGlue(importCatalogToGlueRequest);
    }

    @Override
    public ListBlueprintsResult listBlueprints(ListBlueprintsRequest listBlueprintsRequest) {
        return null;
    }

    @Override
    public ListCrawlersResult listCrawlers(ListCrawlersRequest listCrawlersRequest) {
        return decoratedAwsGlue.listCrawlers(listCrawlersRequest);
    }

    @Override
    public ListCustomEntityTypesResult listCustomEntityTypes(ListCustomEntityTypesRequest listCustomEntityTypesRequest) {
        return null;
    }

    @Override
    public ListDevEndpointsResult listDevEndpoints(ListDevEndpointsRequest listDevEndpointsRequest) {
        return decoratedAwsGlue.listDevEndpoints(listDevEndpointsRequest);
    }

    @Override
    public ListJobsResult listJobs(ListJobsRequest listJobsRequest) {
        return decoratedAwsGlue.listJobs(listJobsRequest);
    }

    @Override
    public ListMLTransformsResult listMLTransforms(ListMLTransformsRequest listMLTransformsRequest) {
        return decoratedAwsGlue.listMLTransforms(listMLTransformsRequest);
    }

    @Override
    public ListRegistriesResult listRegistries(ListRegistriesRequest listRegistriesRequest) {
        return decoratedAwsGlue.listRegistries(listRegistriesRequest);
    }

    @Override
    public ListSchemaVersionsResult listSchemaVersions(ListSchemaVersionsRequest listSchemaVersionsRequest) {
        return decoratedAwsGlue.listSchemaVersions(listSchemaVersionsRequest);
    }

    @Override
    public ListSchemasResult listSchemas(ListSchemasRequest listSchemasRequest) {
        return decoratedAwsGlue.listSchemas(listSchemasRequest);
    }

    @Override
    public ListSessionsResult listSessions(ListSessionsRequest listSessionsRequest) {
        return null;
    }

    @Override
    public ListStatementsResult listStatements(ListStatementsRequest listStatementsRequest) {
        return null;
    }

    @Override
    public ListTriggersResult listTriggers(ListTriggersRequest listTriggersRequest) {
        return decoratedAwsGlue.listTriggers(listTriggersRequest);
    }

    @Override
    public ListWorkflowsResult listWorkflows(ListWorkflowsRequest listWorkflowsRequest) {
        return decoratedAwsGlue.listWorkflows(listWorkflowsRequest);
    }

    @Override
    public PutDataCatalogEncryptionSettingsResult putDataCatalogEncryptionSettings(PutDataCatalogEncryptionSettingsRequest putDataCatalogEncryptionSettingsRequest) {
        return decoratedAwsGlue.putDataCatalogEncryptionSettings(putDataCatalogEncryptionSettingsRequest);
    }

    @Override
    public PutResourcePolicyResult putResourcePolicy(PutResourcePolicyRequest putResourcePolicyRequest) {
        return decoratedAwsGlue.putResourcePolicy(putResourcePolicyRequest);
    }

    @Override
    public PutSchemaVersionMetadataResult putSchemaVersionMetadata(PutSchemaVersionMetadataRequest putSchemaVersionMetadataRequest) {
        return decoratedAwsGlue.putSchemaVersionMetadata(putSchemaVersionMetadataRequest);
    }

    @Override
    public PutWorkflowRunPropertiesResult putWorkflowRunProperties(PutWorkflowRunPropertiesRequest putWorkflowRunPropertiesRequest) {
        return decoratedAwsGlue.putWorkflowRunProperties(putWorkflowRunPropertiesRequest);
    }

    @Override
    public QuerySchemaVersionMetadataResult querySchemaVersionMetadata(QuerySchemaVersionMetadataRequest querySchemaVersionMetadataRequest) {
        return decoratedAwsGlue.querySchemaVersionMetadata(querySchemaVersionMetadataRequest);
    }

    @Override
    public RegisterSchemaVersionResult registerSchemaVersion(RegisterSchemaVersionRequest registerSchemaVersionRequest) {
        return decoratedAwsGlue.registerSchemaVersion(registerSchemaVersionRequest);
    }

    @Override
    public RemoveSchemaVersionMetadataResult removeSchemaVersionMetadata(RemoveSchemaVersionMetadataRequest removeSchemaVersionMetadataRequest) {
        return decoratedAwsGlue.removeSchemaVersionMetadata(removeSchemaVersionMetadataRequest);
    }

    @Override
    public ResetJobBookmarkResult resetJobBookmark(ResetJobBookmarkRequest resetJobBookmarkRequest) {
        return decoratedAwsGlue.resetJobBookmark(resetJobBookmarkRequest);
    }

    @Override
    public SearchTablesResult searchTables(SearchTablesRequest searchTablesRequest) {
        return decoratedAwsGlue.searchTables(searchTablesRequest);
    }

    @Override
    public StartBlueprintRunResult startBlueprintRun(StartBlueprintRunRequest startBlueprintRunRequest) {
        return null;
    }

    @Override
    public StartCrawlerResult startCrawler(StartCrawlerRequest startCrawlerRequest) {
        return decoratedAwsGlue.startCrawler(startCrawlerRequest);
    }

    @Override
    public StartCrawlerScheduleResult startCrawlerSchedule(StartCrawlerScheduleRequest startCrawlerScheduleRequest) {
        return decoratedAwsGlue.startCrawlerSchedule(startCrawlerScheduleRequest);
    }

    @Override
    public StartExportLabelsTaskRunResult startExportLabelsTaskRun(StartExportLabelsTaskRunRequest startExportLabelsTaskRunRequest) {
        return decoratedAwsGlue.startExportLabelsTaskRun(startExportLabelsTaskRunRequest);
    }

    @Override
    public StartImportLabelsTaskRunResult startImportLabelsTaskRun(StartImportLabelsTaskRunRequest startImportLabelsTaskRunRequest) {
        return decoratedAwsGlue.startImportLabelsTaskRun(startImportLabelsTaskRunRequest);
    }

    @Override
    public StartJobRunResult startJobRun(StartJobRunRequest startJobRunRequest) {
        return decoratedAwsGlue.startJobRun(startJobRunRequest);
    }

    @Override
    public StartMLEvaluationTaskRunResult startMLEvaluationTaskRun(StartMLEvaluationTaskRunRequest startMLEvaluationTaskRunRequest) {
        return decoratedAwsGlue.startMLEvaluationTaskRun(startMLEvaluationTaskRunRequest);
    }

    @Override
    public StartMLLabelingSetGenerationTaskRunResult startMLLabelingSetGenerationTaskRun(StartMLLabelingSetGenerationTaskRunRequest startMLLabelingSetGenerationTaskRunRequest) {
        return decoratedAwsGlue.startMLLabelingSetGenerationTaskRun(startMLLabelingSetGenerationTaskRunRequest);
    }

    @Override
    public StartTriggerResult startTrigger(StartTriggerRequest startTriggerRequest) {
        return decoratedAwsGlue.startTrigger(startTriggerRequest);
    }

    @Override
    public StartWorkflowRunResult startWorkflowRun(StartWorkflowRunRequest startWorkflowRunRequest) {
        return decoratedAwsGlue.startWorkflowRun(startWorkflowRunRequest);
    }

    @Override
    public StopCrawlerResult stopCrawler(StopCrawlerRequest stopCrawlerRequest) {
        return decoratedAwsGlue.stopCrawler(stopCrawlerRequest);
    }

    @Override
    public StopCrawlerScheduleResult stopCrawlerSchedule(StopCrawlerScheduleRequest stopCrawlerScheduleRequest) {
        return decoratedAwsGlue.stopCrawlerSchedule(stopCrawlerScheduleRequest);
    }

    @Override
    public StopSessionResult stopSession(StopSessionRequest stopSessionRequest) {
        return null;
    }

    @Override
    public StopTriggerResult stopTrigger(StopTriggerRequest stopTriggerRequest) {
        return decoratedAwsGlue.stopTrigger(stopTriggerRequest);
    }

    @Override
    public StopWorkflowRunResult stopWorkflowRun(StopWorkflowRunRequest stopWorkflowRunRequest) {
        return decoratedAwsGlue.stopWorkflowRun(stopWorkflowRunRequest);
    }

    @Override
    public TagResourceResult tagResource(TagResourceRequest tagResourceRequest) {
        return decoratedAwsGlue.tagResource(tagResourceRequest);
    }

    @Override
    public UntagResourceResult untagResource(UntagResourceRequest untagResourceRequest) {
        return decoratedAwsGlue.untagResource(untagResourceRequest);
    }

    @Override
    public UpdateBlueprintResult updateBlueprint(UpdateBlueprintRequest updateBlueprintRequest) {
        return null;
    }

    @Override
    public UpdateClassifierResult updateClassifier(UpdateClassifierRequest updateClassifierRequest) {
        return decoratedAwsGlue.updateClassifier(updateClassifierRequest);
    }

    @Override
    public UpdateColumnStatisticsForPartitionResult updateColumnStatisticsForPartition(UpdateColumnStatisticsForPartitionRequest updateColumnStatisticsForPartitionRequest) {
        return decoratedAwsGlue.updateColumnStatisticsForPartition(updateColumnStatisticsForPartitionRequest);
    }

    @Override
    public UpdateColumnStatisticsForTableResult updateColumnStatisticsForTable(UpdateColumnStatisticsForTableRequest updateColumnStatisticsForTableRequest) {
        return decoratedAwsGlue.updateColumnStatisticsForTable(updateColumnStatisticsForTableRequest);
    }

    @Override
    public UpdateConnectionResult updateConnection(UpdateConnectionRequest updateConnectionRequest) {
        return decoratedAwsGlue.updateConnection(updateConnectionRequest);
    }

    @Override
    public UpdateCrawlerResult updateCrawler(UpdateCrawlerRequest updateCrawlerRequest) {
        return decoratedAwsGlue.updateCrawler(updateCrawlerRequest);
    }

    @Override
    public UpdateCrawlerScheduleResult updateCrawlerSchedule(UpdateCrawlerScheduleRequest updateCrawlerScheduleRequest) {
        return decoratedAwsGlue.updateCrawlerSchedule(updateCrawlerScheduleRequest);
    }

    @Override
    public UpdateDatabaseResult updateDatabase(UpdateDatabaseRequest updateDatabaseRequest) {
        return decoratedAwsGlue.updateDatabase(updateDatabaseRequest);
    }

    @Override
    public UpdateDevEndpointResult updateDevEndpoint(UpdateDevEndpointRequest updateDevEndpointRequest) {
        return decoratedAwsGlue.updateDevEndpoint(updateDevEndpointRequest);
    }

    @Override
    public UpdateJobResult updateJob(UpdateJobRequest updateJobRequest) {
        return decoratedAwsGlue.updateJob(updateJobRequest);
    }

    @Override
    public UpdateMLTransformResult updateMLTransform(UpdateMLTransformRequest updateMLTransformRequest) {
        return decoratedAwsGlue.updateMLTransform(updateMLTransformRequest);
    }

    @Override
    public UpdatePartitionResult updatePartition(UpdatePartitionRequest updatePartitionRequest) {
        return decoratedAwsGlue.updatePartition(updatePartitionRequest);
    }

    @Override
    public UpdateRegistryResult updateRegistry(UpdateRegistryRequest updateRegistryRequest) {
        return decoratedAwsGlue.updateRegistry(updateRegistryRequest);
    }

    @Override
    public UpdateSchemaResult updateSchema(UpdateSchemaRequest updateSchemaRequest) {
        return decoratedAwsGlue.updateSchema(updateSchemaRequest);
    }

    @Override
    public UpdateTableResult updateTable(UpdateTableRequest updateTableRequest) {
        return decoratedAwsGlue.updateTable(updateTableRequest);
    }

    @Override
    public UpdateTriggerResult updateTrigger(UpdateTriggerRequest updateTriggerRequest) {
        return decoratedAwsGlue.updateTrigger(updateTriggerRequest);
    }

    @Override
    public UpdateUserDefinedFunctionResult updateUserDefinedFunction(UpdateUserDefinedFunctionRequest updateUserDefinedFunctionRequest) {
        return decoratedAwsGlue.updateUserDefinedFunction(updateUserDefinedFunctionRequest);
    }

    @Override
    public UpdateWorkflowResult updateWorkflow(UpdateWorkflowRequest updateWorkflowRequest) {
        return decoratedAwsGlue.updateWorkflow(updateWorkflowRequest);
    }

    @Override
    public void shutdown() {
        decoratedAwsGlue.shutdown();
    }

    @Override
    public ResponseMetadata getCachedResponseMetadata(AmazonWebServiceRequest amazonWebServiceRequest) {
        return decoratedAwsGlue.getCachedResponseMetadata(amazonWebServiceRequest);
    }

    @Override
    public ResumeWorkflowRunResult resumeWorkflowRun(ResumeWorkflowRunRequest resumeWorkflowRunRequest) {
        return decoratedAwsGlue.resumeWorkflowRun(resumeWorkflowRunRequest);
    }

    @Override
    public RunStatementResult runStatement(RunStatementRequest runStatementRequest) {
        return null;
    }

    @Override
    public GetResourcePoliciesResult getResourcePolicies(GetResourcePoliciesRequest getResourcePoliciesRequest) {
        return decoratedAwsGlue.getResourcePolicies(getResourcePoliciesRequest);
    }
}
